import { Button, LineEdit, SpinBox, ProgressIndicator } from "std-widgets.slint";
export component MainWindow inherits Window {
    title: "spliter";
    width: 400px;
    height: 400px;

    in-out property <string> text:"请选择文件或输入路径";
    in-out property <string> input;
    in-out property <string> output:"/data";
    in-out property <int> header_number:2;
    in-out property <int> col_index:1;
    in-out property <int> progress:50;



    callback selectfile()->string; //选择文件
    callback splitbook(string,string,int,int);
    


    VerticalLayout {
        Rectangle { 
            background: blue; 
            LineEdit {
                font-size: 14px;
                width: 200px;
                x: 50px;
                placeholder-text: text;
            }
            LineEdit {
                font-size: 14px;
                width: 200px;
                x: 50px;
                y:220px;
                placeholder-text: "默认输出路径："+output;
            }
            Button {
                text: "选择文件";
                x:260px;
                clicked => {
                    root.text = root.selectfile();
                    root.input = root.text;
                }
            }
            Button {
                text: "开始";
                y:220px;
                x:260px;
                clicked => {
                    root.splitbook(input,output,header_number,col_index);
                }
            }
            Text {
                x:50px;
                y:123px;
                text: "表头行数";
                font-size: 16px;
                color: white;
            }
            Text {
                x:208px;
                y:123px;
                text: "基准列";
                font-size: 16px;
                color: white;
            }
            SpinBox {
                x:50px;
                y:150px;
                value:header_number;
            }
            SpinBox {
                x:208px;
                y:150px;
                value: col_index;
            }
            ProgressIndicator {
                width: 286px;
                height: 20px;
                x:50px;
                y:260px;
                progress: progress/100;
                
            }
        }
    }
}